/*
    artifact generator: C:\My\wizzi\stfnbssl\wizzi.v07\node_modules\wizzi-legacy-v5\lib\artifacts\js\module\gen\main.js
    primary source IttfDocument: c:\my\wizzi\stfnbssl\wizzi.v07\packages\wizzi-core\lib\artifacts\wfschema\model\gen\ittf\wfschema-model.js.ittf
    utc time: Tue, 16 May 2023 07:53:35 GMT
*/
'use strict';
// generated by v5-wizzi-js.artifacts.js.module.main
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }
var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; desc = parent = undefined; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

var util = require('util');
var path = require('path');
var _ = require('lodash');
var chalk = require('chalk');
var wzutils = require('wizzi-utils');
var verify = wzutils.verify;
var _md = module.exports = {};
var wzSourceLineInfo = (function () {
    function wzSourceLineInfo(row, col, sourceKey) {
        _classCallCheck(this, wzSourceLineInfo);
        this.row = row;
        this.col = col;
        this.sourceKey = sourceKey;
    }
    wzSourceLineInfo.prototype.toString = function(instance) {
        if (instance) {
            return 'row: ' + this.row + ', col: ' + this.col + ', file: ' + instance.wzSourceFilepath(this.sourceKey);
        }
        else {
            return 'row: ' + this.row + ', col: ' + this.col + ', sourceKey: ' + this.sourceKey;
        }
    }
    return wzSourceLineInfo;
})();

_md.wzSourceLineInfo = wzSourceLineInfo;
var wzschemaBase = (function () {
    function wzschemaBase(name, sourceLineInfo) {
        _classCallCheck(this, wzschemaBase);
        this.wzName = name || '';
        this.wzParent = null;
        this.wzSourceLineInfo = sourceLineInfo;
        this.wzChildren = [];
    }
    wzschemaBase.prototype.wzRoot = function() {
        return this.wzParent == null ? this : this.wzParent.wzRoot();
    }
    wzschemaBase.prototype.wzSourceFilepath = function(sourceKey) {
        var sk = sourceKey || this.wzSourceLineInfo.sourceKey;
        return this.wzRoot().loadHistory.getIttfDocumentUri(sk);
    }
    wzschemaBase.prototype.wzSourceErrorLines = function(node, message) {
        return this.wzRoot().loadHistory.getIttfDocumentErrorLines(node.u, {
                row: node.r, 
                col: node.c, 
                description: message
            }, true);
    }
    wzschemaBase.prototype.wzVerify = function() {
    }
    wzschemaBase.prototype.wzInitialize = function() {
    }
    wzschemaBase.prototype.wzInitializeAsync = function(ctx, callback) {
        callback(null);
    }
    wzschemaBase.prototype.wzAddChild = function(node) {
        node.wzParent = this;
        this.wzChildren.push(node);
    }
    wzschemaBase.prototype.wzAddChildToColl = function(node, coll) {
        node.wzParent = this;
        node.wzMoved = true;
        coll.push(node);
    }
    wzschemaBase.prototype.wzMoveChildToColl = function(node, coll, fromColl) {
        var index = fromColl.indexOf(node);
        if (index < 0) {
            this.error('wzMoveChildToColl error. The from collection does not contain the node.', node);
        }
        fromColl.splice(index, 1);
        this.wzAddChildToColl(node, coll);
    }
    wzschemaBase.prototype.wzLoadToChildColl = function(child, type, coll) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        item.wzTag = child.n;
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        item.wzParent = this;
        coll.push(item);
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    wzschemaBase.prototype.wzCreateChildColl = function(tag, name, type, coll) {
        var item = new type(name, this.wzSourceLineInfo);
        item.wzTag = tag;
        item.wzParent = this;
        item.wzCreated = true;
        coll.push(item);
        return item;
    }
    wzschemaBase.prototype.wzLoadToChildren = function(child, type) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        item.wzTag = child.n;
        item.wzParent = this;
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        this.wzChildren.push(item);
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    wzschemaBase.prototype.wzLoadOneToOne = function(child, type, fieldName) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        item.wzParent = this;
        this[fieldName] = item;
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    wzschemaBase.prototype.wzRemove = function(fromColl) {
        var index = fromColl.indexOf(this);
        if (index < 0) {
            this.error('wzRemove error. The from collection does not contain the node.', this);
        }
        fromColl.splice(index, 1);
    }
    wzschemaBase.prototype.error = function(message, node) {
        throw new _md.wzschemaModelException(message, node, this);
    }
    return wzschemaBase;
})();

_md.wzschemaBase = wzschemaBase;
// element wzschema
var wzschema = (function (wzschemaBase) {
    _inherits(wzschema, wzschemaBase);
    function wzschema(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(wzschema.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, wzschema);
        this.wzElement = "wzschema";
        // relation element
        this.elements = [];
    }
    wzschema.prototype.addElement = function(name, sourceLineInfo) {
        var retval = new _md.element(name, sourceLineInfo);
        retval.wzParent = this;
        this.elements.push(retval);
        return retval;
    }
    wzschema.prototype.getElement = function(name) {
        var found = null;
        this.elements.forEach(function(item) {
            found = found || (item.wzName === name ? item : null);
        });
        return found;
    }
    wzschema.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'e') {
            return this.wzLoadToChildColl(child, _md.element, this.elements);
        }
        return false;
    }
    wzschema.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.wzschemaModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    wzschema.prototype.wzVerify = function(ctx) {
        this.elements.forEach((item) => {
            item.wzVerify(ctx);
        });
        _md.wzschemaBase.prototype.wzVerify.call(this, ctx);
    }
    wzschema.prototype.wzInitialize = function(ctx) {
        this.elements.forEach((item) => {
            item.wzInitialize(ctx);
        });
        _md.wzschemaBase.prototype.wzInitialize.call(this, ctx);
    }
    return wzschema;
})(wzschemaBase);

_md.wzschema = wzschema;
// element jsInclude
var jsInclude = (function (wzschemaBase) {
    _inherits(jsInclude, wzschemaBase);
    function jsInclude(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(jsInclude.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, jsInclude);
        this.wzElement = "jsInclude";
        this.js_module_items = [];
    }
    jsInclude.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'module') {
            // generated by wizzi/lib/wizzi/models/bootstrap/t/wfschema/t/element_load;
            this.js_module_items.push(child);
            var err, wizziModel;
            this.wzRoot().wzFactory.loadModelFromMtree( //;
                'js',  //;
                { nodes: [ child ], loadHistory: this.wzRoot().loadHistory }, //;
                function(cberr, cbwizziModel) { //;
                    err = cberr;
                    wizziModel = cbwizziModel;
                });
            this.get_js = function(callback) { //;
                // We must wait until the async loadModelFromMtree(..) has returned a wizziModel or an err;
                var iv = setInterval(function() { //;
                    if (err || wizziModel) { //;
                        clearInterval(iv);
                        if (callback) { //;
                            callback(err, wizziModel);
                            callback = null;
                        } //;
                    } //;
                }, 100);
            };
            return true;
        }
        return false;
    }
    jsInclude.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.wzschemaModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    return jsInclude;
})(wzschemaBase);

_md.jsInclude = jsInclude;
// element element
var element = (function (wzschemaBase) {
    _inherits(element, wzschemaBase);
    function element(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(element.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, element);
        this.wzElement = "element";
        this.isRoot = false;
        // relation attribute
        this.attributes = [];
        // relation relation
        this.relations = [];
    }
    element.prototype.addAttribute = function(name, sourceLineInfo) {
        var retval = new _md.attribute(name, sourceLineInfo);
        retval.wzParent = this;
        this.attributes.push(retval);
        return retval;
    }
    element.prototype.getAttribute = function(name) {
        var found = null;
        this.attributes.forEach(function(item) {
            found = found || (item.wzName === name ? item : null);
        });
        return found;
    }
    element.prototype.addRelation = function(name, sourceLineInfo) {
        var retval = new _md.relation(name, sourceLineInfo);
        retval.wzParent = this;
        this.relations.push(retval);
        return retval;
    }
    element.prototype.getRelation = function(name) {
        var found = null;
        this.relations.forEach(function(item) {
            found = found || (item.wzName === name ? item : null);
        });
        return found;
    }
    element.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'a') {
            return this.wzLoadToChildColl(child, _md.attribute, this.attributes);
        }
        if (name === 'r') {
            return this.wzLoadToChildColl(child, _md.relation, this.relations);
        }
        if (name === 'tag') {
            this.tag = child.v; return true;
        }
        if (name === 'super') {
            this.super = child.v; return true;
        }
        if (name === 'is-root') {
            this.isRoot = parseboolean(child.v, true, child); return true;
        }
        else if (name === 'is_root') {
            this.isRoot = parseboolean(child.v, true, child); return true;
        }
        return false;
    }
    element.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.wzschemaModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    element.prototype.wzVerify = function(ctx) {
        this.attributes.forEach((item) => {
            item.wzVerify(ctx);
        });
        this.relations.forEach((item) => {
            item.wzVerify(ctx);
        });
        _md.wzschemaBase.prototype.wzVerify.call(this, ctx);
    }
    element.prototype.wzInitialize = function(ctx) {
        this.attributes.forEach((item) => {
            item.wzInitialize(ctx);
        });
        this.relations.forEach((item) => {
            item.wzInitialize(ctx);
        });
        _md.wzschemaBase.prototype.wzInitialize.call(this, ctx);
    }
    return element;
})(wzschemaBase);

_md.element = element;
// element relation
var relation = (function (wzschemaBase) {
    _inherits(relation, wzschemaBase);
    function relation(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(relation.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, relation);
        this.wzElement = "relation";
    }
    relation.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'type') {
            this.type = child.v; return true;
        }
        return false;
    }
    relation.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.wzschemaModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    return relation;
})(wzschemaBase);

_md.relation = relation;
// element attribute
var attribute = (function (wzschemaBase) {
    _inherits(attribute, wzschemaBase);
    function attribute(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(attribute.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, attribute);
        this.wzElement = "attribute";
        this.defaultWhenDeclared = false;
    }
    attribute.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'tag') {
            this.tag = child.v; return true;
        }
        if (name === 'type') {
            this.type = child.v; return true;
        }
        if (name === 'default') {
            this.default = child.v; return true;
        }
        if (name === 'default-when-declared') {
            this.defaultWhenDeclared = parseboolean(child.v, true, child); return true;
        }
        else if (name === 'default_when_declared') {
            this.defaultWhenDeclared = parseboolean(child.v, true, child); return true;
        }
        return false;
    }
    attribute.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.wzschemaModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    return attribute;
})(wzschemaBase);

_md.attribute = attribute;
_md.__tagElementMapping = { 'e': 'element', 'a': 'attribute', 'r': 'relation' };
// model/replaceUnknownElement( )
var wzschemaModelException = (function () {
    function wzschemaModelException(message, node, instance) {
        _classCallCheck(this, wzschemaModelException);
        // VIA 14/2/21 (pollutes log) set this.node = node
        // VIA 14/2/21 (pollutes log) set this.instance = instance
        if (node && instance) {
            this.message = message + ', wzElement: ' + node.wzElement + ', wzName:' + (node.wzName || '') + ', row:' + node.r + ', col:' + node.c + ', source:' + instance.wzSourceFilepath(node.u);
            this.errorLines = instance.wzSourceErrorLines(node, message);
        }
        else if (instance) {
            this.message = message + instance.wzSourceLineInfo.toString(instance);
        }
        else {
            this.message = message;
        }
        console.error('message', this.message);
        this.stack = (new Error()).stack;
    }
    wzschemaModelException.prototype.toString = function() {
        var msg = [];
        msg.push(chalk.red('Error: ' + this.message));
        msg.push(chalk.red('  name: wzschemaModelException'));
        if (this.node) {
            msg.push(chalk.yellow('  row: ' + this.node.r + ', col: ' + this.node.c));
        }
        if (this.instance) {
            if (this.node) {
                msg.push(chalk.yellow('  uri: ' + this.instance.wzSourceFilepath(this.node.u)));
            }
            else {
                msg.push(chalk.yellow('  uri: ' + this.instance.wzSourceLineInfo.toString(this.instance)));
            }
        }
        else {
            msg.push(chalk.yellow('  uri: unknown'));
        }
        if (this.errorLines) {
            var i, i_items=this.errorLines, i_len=this.errorLines.length, line;
            for (i=0; i<i_len; i++) {
                line = this.errorLines[i];
                msg.push(chalk.yellow('  ' + line));
            }
        }
        return msg.join('\n');
    }
    return wzschemaModelException;
})();

_md.wzschemaModelException = wzschemaModelException;
var wzschemaContext = (function () {
    function wzschemaContext() {
        _classCallCheck(this, wzschemaContext);
        this.validationErrors = [];
    }
    wzschemaContext.prototype.schemaIsValid = function() {
        return this.validationErrors.length == 0;
    }
    wzschemaContext.prototype.addError = function(message, node) {
        var at = node ? ' At ' + node.wzSourceLineInfo.toString(node) : '';
        this.validationErrors.push(message + at);
    }
    return wzschemaContext;
})();

_md.wzschemaContext = wzschemaContext;
function parsestring(value, defaultValue, node) {
    if (isEmpty( value )) {
        return defaultValue;
    }
    return value;
}
function parseboolean(value, defaultValue, node) {
    if (isEmpty( value )) {
        return defaultValue;
    }
    if (!isBoolean(value)) {
        throw new wzschemaModelException('Must be a boolean value (\"true\" or \"false\"), got:' + value, node);
    }
    return value === 'true' ? true : false;
}
function isString(value) {
    return (typeof value === 'string' || value instanceof String);
}
function isEmpty(value) {
    return !isString( value ) || value.length === 0;
}
function isBoolean(value) {
    return value === 'true' || value === 'false';
}

