/*
    artifact generator: C:\My\wizzi\stfnbssl\wizzi.plugins\packages\wizzi.plugin.wfschema\node_modules\wizzi-js\lib\artifacts\js\module\gen\main.js
    package: wizzi-js@0.7.13
    primary source IttfDocument: C:\My\wizzi\stfnbssl\wizzi.plugins\packages\wizzi.plugin.wfschema\lib\artifacts\wfschema\model\gen\ittf\wfschema-model.js.ittf
*/
'use strict';
// generated by v6-wizzi-js.artifacts.js.module.main
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }
var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; desc = parent = undefined; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

var util = require('util');
var path = require('path');
var _ = require('lodash');
var chalk = require('chalk');
var wzutils = require('wizzi-utils');
var verify = wzutils.verify;


var _md = module.exports = {};

var wzSourceLineInfo = (function () {
    function wzSourceLineInfo(row, col, sourceKey) {
        _classCallCheck(this, wzSourceLineInfo);
        this.row = row;
        this.col = col;
        this.sourceKey = sourceKey;
    }
    wzSourceLineInfo.prototype.toString = function(instance) {
        if (instance) {
            return 'row: ' + this.row + ', col: ' + this.col + ', file: ' + instance.wzSourceFilepath(this.sourceKey);
        }
        else {
            return 'row: ' + this.row + ', col: ' + this.col + ', sourceKey: ' + this.sourceKey;
        }
    }
    return wzSourceLineInfo;
})();

_md.wzSourceLineInfo = wzSourceLineInfo;
var dartBase = (function () {
    function dartBase(name, sourceLineInfo) {
        _classCallCheck(this, dartBase);
        this.wzName = name || '';
        this.wzParent = null;
        this.wzSourceLineInfo = sourceLineInfo;
        this.wzChildren = [];
    }
    dartBase.prototype.wzRoot = function() {
        return this.wzParent == null ? this : this.wzParent.wzRoot();
    }
    dartBase.prototype.wzSourceFilepath = function(sourceKey) {
        var sk = sourceKey || this.wzSourceLineInfo.sourceKey;
        return this.wzRoot().loadHistory.getIttfDocumentUri(sk);
    }
    dartBase.prototype.wzSourceErrorLines = function(node, message) {
        return this.wzRoot().loadHistory.getIttfDocumentErrorLines(node.u, {
                row: node.r, 
                col: node.c, 
                description: message
             }, true);
    }
    dartBase.prototype.wzVerify = function() {
    }
    dartBase.prototype.wzInitialize = function() {
    }
    dartBase.prototype.wzInitializeAsync = function(ctx, callback) {
        callback(null);
    }
    dartBase.prototype.wzAddChild = function(node) {
        node.wzParent = this;
        this.wzChildren.push(node);
    }
    dartBase.prototype.wzAddChildToColl = function(node, coll) {
        node.wzParent = this;
        node.wzMoved = true;
        coll.push(node);
    }
    dartBase.prototype.wzMoveChildToColl = function(node, coll, fromColl) {
        var index = fromColl.indexOf(node);
        if (index < 0) {
            this.error('wzMoveChildToColl error. The from collection does not contain the node.', node)
        }
        fromColl.splice(index, 1);
        this.wzAddChildToColl(node, coll);
    }
    dartBase.prototype.wzLoadToChildColl = function(child, type, coll) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        item.wzTag = child.n;
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        item.wzParent = this;
        coll.push(item);
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    dartBase.prototype.wzCreateChildColl = function(tag, name, type, coll) {
        var item = new type(name, this.wzSourceLineInfo);
        item.wzTag = tag;
        item.wzParent = this;
        item.wzCreated = true;
        coll.push(item);
        return item;
    }
    dartBase.prototype.wzLoadToChildren = function(child, type) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        item.wzTag = child.n;
        item.wzParent = this;
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        this.wzChildren.push(item);
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    dartBase.prototype.wzLoadOneToOne = function(child, type, fieldName) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        item.wzParent = this;
        this[fieldName] = item;
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    dartBase.prototype.wzRemove = function(fromColl) {
        var index = fromColl.indexOf(this);
        if (index < 0) {
            this.error('wzRemove error. The from collection does not contain the node.', this)
        }
        fromColl.splice(index, 1);
    }
    dartBase.prototype.error = function(message, node) {
        throw new _md.dartModelException(message, node, this);
    }
    return dartBase;
})();

_md.dartBase = dartBase;

// element statement
var statement = (function (dartBase) {
    _inherits(statement, dartBase);
    function statement(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(statement.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, statement);
        this.wzElement = "statement";
        // relation statement
        this.statements = [];
    }
    statement.prototype.addStatement = function(name, sourceLineInfo) {
        var retval = new _md.statement(name, sourceLineInfo);
        retval.wzParent = this;
        this.statements.push(retval);
        return retval;
    }
    statement.prototype.getStatement = function(name) {
        var found = null;
        this.statements.forEach(function(item) {
            found = found || (item.wzName === name ? item : null);
        })
        return found;
    }
    statement.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === '#') {
            return this.wzLoadToChildColl(child, _md.statement, this.statements);
        }
        if (name === '(') {
            return this.wzLoadToChildColl(child, _md.paren, this.statements);
        }
        if (name === '+') {
            return this.wzLoadToChildColl(child, _md.taggedline, this.statements);
        }
        if (name === '[') {
            return this.wzLoadToChildColl(child, _md.bracket, this.statements);
        }
        if (name === '{') {
            return this.wzLoadToChildColl(child, _md.block, this.statements);
        }
        if (name === 'if') {
            return this.wzLoadToChildColl(child, _md.xif, this.statements);
        }
        if (name === 'for') {
            return this.wzLoadToChildColl(child, _md.xfor, this.statements);
        }
        if (name === 'dart') {
            return this.wzLoadToChildColl(child, _md.dart, this.statements);
        }
        if (name === 'while') {
            return this.wzLoadToChildColl(child, _md.xwhile, this.statements);
        }
        if (name === 'codeline') {
            return this.wzLoadToChildColl(child, _md.codeline, this.statements);
        }
        return false;
    }
    statement.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
        
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.dartModelException("Tag not recognized: " + item.n, item, this);
            }
        }
        )
    }
    statement.prototype.wzVerify = function(ctx) {
        this.statements.forEach(item => 
        
            item.wzVerify(ctx)
        )
        _md.dartBase.prototype.wzVerify.call(this, ctx);
    }
    statement.prototype.wzInitialize = function(ctx) {
        this.statements.forEach(item => 
        
            item.wzInitialize(ctx)
        )
        _md.dartBase.prototype.wzInitialize.call(this, ctx);
    }
    return statement;
})(dartBase);

_md.statement = statement;
// element codeline
var codeline = (function (statement) {
    _inherits(codeline, statement);
    function codeline(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(codeline.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, codeline);
        this.wzElement = "codeline";
    }
    return codeline;
})(statement);

_md.codeline = codeline;
// element taggedline
var taggedline = (function (statement) {
    _inherits(taggedline, statement);
    function taggedline(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(taggedline.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, taggedline);
        this.wzElement = "taggedline";
    }
    return taggedline;
})(statement);

_md.taggedline = taggedline;
// element dart
var dart = (function (statement) {
    _inherits(dart, statement);
    function dart(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(dart.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, dart);
        this.wzElement = "dart";
    }
    dart.prototype.loadChild = function(child) {
        var ok = false, name = child.n.toLowerCase();
        ok = _md.statement.prototype.loadChild.call(this, child);
        if (!ok) {
            return this.wzLoadToChildColl(child, _md.codeline, this.);
        }
        return ok;
    }
    dart.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
        
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.dartModelException("Tag not recognized: " + item.n, item, this);
            }
        }
        )
    }
    return dart;
})(statement);

_md.dart = dart;
// element block
var block = (function (statement) {
    _inherits(block, statement);
    function block(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(block.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, block);
        this.wzElement = "block";
    }
    return block;
})(statement);

_md.block = block;
// element bracket
var bracket = (function (statement) {
    _inherits(bracket, statement);
    function bracket(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(bracket.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, bracket);
        this.wzElement = "bracket";
    }
    return bracket;
})(statement);

_md.bracket = bracket;
// element paren
var paren = (function (statement) {
    _inherits(paren, statement);
    function paren(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(paren.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, paren);
        this.wzElement = "paren";
    }
    return paren;
})(statement);

_md.paren = paren;
// element xif
var xif = (function (statement) {
    _inherits(xif, statement);
    function xif(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(xif.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, xif);
        this.wzElement = "xif";
    }
    return xif;
})(statement);

_md.xif = xif;
// element xfor
var xfor = (function (statement) {
    _inherits(xfor, statement);
    function xfor(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(xfor.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, xfor);
        this.wzElement = "xfor";
    }
    return xfor;
})(statement);

_md.xfor = xfor;
// element xwhile
var xwhile = (function (statement) {
    _inherits(xwhile, statement);
    function xwhile(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(xwhile.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, xwhile);
        this.wzElement = "xwhile";
    }
    return xwhile;
})(statement);

_md.xwhile = xwhile;
_md.__tagElementMapping = { '#': 'statement', '+': 'taggedline', '{': 'block', '[': 'bracket', '(': 'paren', 'if': 'xif', 'for': 'xfor', 'while': 'xwhile' };
// model/replaceUnknownElement( )
var dartModelException = (function () {
    function dartModelException(message, node, instance) {
        _classCallCheck(this, dartModelException);
        // VIA 14/2/21 (pollutes log) set this.node = node
        // VIA 14/2/21 (pollutes log) set this.instance = instance
        if (node && instance) {
            this.message = message + ', wzElement: ' + node.wzElement + ', wzName:' + (node.wzName || '') + ', row:' + node.r + ', col:' + node.c + ', source:' + instance.wzSourceFilepath(node.u);
            this.errorLines = instance.wzSourceErrorLines(node, message)
            ;
        }
        else if (instance) {
            this.message = message + instance.wzSourceLineInfo.toString(instance);
        }
        else {
            this.message = message;
        }
        console.log("[31m%s[0m", 'message', this.message);
        this.stack = (new Error()).stack;
    }
    dartModelException.prototype.toString = function() {
        var msg = [];
        msg.push(chalk.red('Error: ' + this.message));
        msg.push(chalk.red('  name: dartModelException'));
        if (this.node) {
            msg.push(chalk.yellow('  row: ' + this.node.r + ', col: ' + this.node.c));
        }
        if (this.instance) {
            if (this.node) {
                msg.push(chalk.yellow('  uri: ' + this.instance.wzSourceFilepath(this.node.u)));
            }
            else {
                msg.push(chalk.yellow('  uri: ' + this.instance.wzSourceLineInfo.toString(this.instance)));
            }
        }
        else {
            msg.push(chalk.yellow('  uri: unknown'));
        }
        if (this.errorLines) {
            var i, i_items=this.errorLines, i_len=this.errorLines.length, line;
            for (i=0; i<i_len; i++) {
                line = this.errorLines[i];
                msg.push(chalk.yellow('  ' + line));
            }
        }
        return msg.join('\n');
    }
    return dartModelException;
})();

_md.dartModelException = dartModelException;
var dartContext = (function () {
    function dartContext() {
        _classCallCheck(this, dartContext);
        this.validationErrors = [];
    }
    dartContext.prototype.schemaIsValid = function() {
        return this.validationErrors.length == 0;
    }
    dartContext.prototype.addError = function(message, node) {
        var at = node ? ' At ' + node.wzSourceLineInfo.toString(node) : '';
        this.validationErrors.push(message + at)
    }
    return dartContext;
})();

_md.dartContext = dartContext;

