/*
    artifact generator: C:\My\wizzi\stfnbssl\wizzi\node_modules\wizzi-legacy-v5\lib\artifacts\js\module\gen\main.js
    primary source IttfDocument: c:\my\wizzi\stfnbssl\wizzi\packages\wizzi-core\lib\artifacts\wfschema\model\gen\ittf\wfschema-model.js.ittf
    utc time: Thu, 02 Mar 2023 19:10:08 GMT
*/
'use strict';
// generated by v5-wizzi-js.artifacts.js.module.main
function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }
var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; desc = parent = undefined; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

var util = require('util');
var path = require('path');
var _ = require('lodash');
var chalk = require('chalk');
var wzutils = require('wizzi-utils');
var verify = wzutils.verify;
var _md = module.exports = {};
var wzSourceLineInfo = (function () {
    function wzSourceLineInfo(row, col, sourceKey) {
        _classCallCheck(this, wzSourceLineInfo);
        this.row = row;
        this.col = col;
        this.sourceKey = sourceKey;
    }
    wzSourceLineInfo.prototype.toString = function(instance) {
        if (instance) {
            return 'row: ' + this.row + ', col: ' + this.col + ', file: ' + instance.wzSourceFilepath(this.sourceKey);
        }
        else {
            return 'row: ' + this.row + ', col: ' + this.col + ', sourceKey: ' + this.sourceKey;
        }
    }
    return wzSourceLineInfo;
})();

_md.wzSourceLineInfo = wzSourceLineInfo;
var rdbmsBase = (function () {
    function rdbmsBase(name, sourceLineInfo) {
        _classCallCheck(this, rdbmsBase);
        this.wzName = name || '';
        this.wzParent = null;
        this.wzSourceLineInfo = sourceLineInfo;
        this.wzChildren = [];
    }
    rdbmsBase.prototype.wzRoot = function() {
        return this.wzParent == null ? this : this.wzParent.wzRoot();
    }
    rdbmsBase.prototype.wzSourceFilepath = function(sourceKey) {
        var sk = sourceKey || this.wzSourceLineInfo.sourceKey;
        return this.wzRoot().loadHistory.getIttfDocumentUri(sk);
    }
    rdbmsBase.prototype.wzSourceErrorLines = function(node, message) {
        return this.wzRoot().loadHistory.getIttfDocumentErrorLines(node.u, {
                row: node.r, 
                col: node.c, 
                description: message
            }, true);
    }
    rdbmsBase.prototype.wzVerify = function() {
    }
    rdbmsBase.prototype.wzInitialize = function() {
    }
    rdbmsBase.prototype.wzInitializeAsync = function(ctx, callback) {
        callback(null);
    }
    rdbmsBase.prototype.wzAddChild = function(node) {
        node.wzParent = this;
        this.wzChildren.push(node);
    }
    rdbmsBase.prototype.wzAddChildToColl = function(node, coll) {
        node.wzParent = this;
        node.wzMoved = true;
        coll.push(node);
    }
    rdbmsBase.prototype.wzMoveChildToColl = function(node, coll, fromColl) {
        var index = fromColl.indexOf(node);
        if (index < 0) {
            this.error('wzMoveChildToColl error. The from collection does not contain the node.', node);
        }
        fromColl.splice(index, 1);
        this.wzAddChildToColl(node, coll);
    }
    rdbmsBase.prototype.wzLoadToChildColl = function(child, type, coll) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        item.wzTag = child.n;
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        item.wzParent = this;
        coll.push(item);
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    rdbmsBase.prototype.wzCreateChildColl = function(tag, name, type, coll) {
        var item = new type(name, this.wzSourceLineInfo);
        item.wzTag = tag;
        item.wzParent = this;
        item.wzCreated = true;
        coll.push(item);
        return item;
    }
    rdbmsBase.prototype.wzLoadToChildren = function(child, type) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        item.wzTag = child.n;
        item.wzParent = this;
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        this.wzChildren.push(item);
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    rdbmsBase.prototype.wzLoadOneToOne = function(child, type, fieldName) {
        var item = new type(child.v, new wzSourceLineInfo(child.r, child.c, child.u));
        if (child.wzMTreeData) {
            item.wzMTreeData = child.wzMTreeData;
        }
        item.wzParent = this;
        this[fieldName] = item;
        if (item.loadFromNode) {
            item.loadFromNode(child);
        }
        return true;
    }
    rdbmsBase.prototype.wzRemove = function(fromColl) {
        var index = fromColl.indexOf(this);
        if (index < 0) {
            this.error('wzRemove error. The from collection does not contain the node.', this);
        }
        fromColl.splice(index, 1);
    }
    rdbmsBase.prototype.error = function(message, node) {
        throw new _md.rdbmsModelException(message, node, this);
    }
    rdbmsBase.prototype.toJsonProperties = function(result) {
        result.wzElement = this.wzElement;
        result.wzTag = this.wzTag;
        result.wzName = this.wzName;
    }
    rdbmsBase.prototype.toJsonChildren = function(result) {
        if (this.wzChildren.length > 0) {
            var children = [];
            this.wzChildren.forEach((item) => {
                children.push(item.toJson());
            });
            result.wzChildren = children;
        }
    }
    return rdbmsBase;
})();

_md.rdbmsBase = rdbmsBase;
// element rdbms
var rdbms = (function (rdbmsBase) {
    _inherits(rdbms, rdbmsBase);
    function rdbms(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(rdbms.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, rdbms);
        this.wzElement = "rdbms";
        // relation item
        this.items = [];
        // relation ittfPanel
        this.ittfPanels = [];
    }
    rdbms.prototype.addItem = function(name, sourceLineInfo) {
        var retval = new _md.item(name, sourceLineInfo);
        retval.wzParent = this;
        this.items.push(retval);
        return retval;
    }
    rdbms.prototype.getItem = function(name) {
        var found = null;
        this.items.forEach(function(item) {
            found = found || (item.wzName === name ? item : null);
        });
        return found;
    }
    rdbms.prototype.addIttfPanel = function(name, sourceLineInfo) {
        var retval = new _md.ittfPanel(name, sourceLineInfo);
        retval.wzParent = this;
        this.ittfPanels.push(retval);
        return retval;
    }
    rdbms.prototype.getIttfPanel = function(name) {
        var found = null;
        this.ittfPanels.forEach(function(item) {
            found = found || (item.wzName === name ? item : null);
        });
        return found;
    }
    rdbms.prototype.toJson = function() {
        var result = {};
        this.toJsonProperties(result);
        this.toJsonChildren(result);
        return result;
    }
    rdbms.prototype.toJsonProperties = function(result) {
        _md.rdbmsBase.prototype.toJsonProperties.call(this, result);
        if (this.__jsonProps) {
            for (var k in this.__jsonProps) {
                result[k] = this.__jsonProps[k];
            }
        }
    }
    rdbms.prototype.toJsonChildren = function(result) {
        _md.rdbmsBase.prototype.toJsonChildren.call(this, result);
        var items, item;
        items = [];
        this.items.forEach((item) => {
            items.push(item.toJson());
        });
        result['items'] = items;
        items = [];
        this.ittfPanels.forEach((item) => {
            items.push(item.toJson());
        });
        result['ittfPanels'] = items;
    }
    rdbms.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'item') {
            return this.wzLoadToChildColl(child, _md.item, this.items);
        }
        if (name === 'ittfpanel') {
            return this.wzLoadToChildColl(child, _md.ittfPanel, this.ittfPanels);
        }
        if (name === 'ittf-panel') {
            return this.wzLoadToChildColl(child, _md.ittfPanel, this.ittfPanels);
        }
        return false;
    }
    rdbms.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.rdbmsModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    rdbms.prototype.wzVerify = function(ctx) {
        this.items.forEach((item) => {
            item.wzVerify(ctx);
        });
        this.ittfPanels.forEach((item) => {
            item.wzVerify(ctx);
        });
        _md.rdbmsBase.prototype.wzVerify.call(this, ctx);
    }
    rdbms.prototype.wzInitialize = function(ctx) {
        this.items.forEach((item) => {
            item.wzInitialize(ctx);
        });
        this.ittfPanels.forEach((item) => {
            item.wzInitialize(ctx);
        });
        _md.rdbmsBase.prototype.wzInitialize.call(this, ctx);
    }
    return rdbms;
})(rdbmsBase);

_md.rdbms = rdbms;
// element item
var item = (function (rdbmsBase) {
    _inherits(item, rdbmsBase);
    function item(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(item.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, item);
        this.wzElement = "item";
    }
    item.prototype.toJson = function() {
        var result = {};
        this.toJsonProperties(result);
        this.toJsonChildren(result);
        return result;
    }
    item.prototype.toJsonProperties = function(result) {
        _md.rdbmsBase.prototype.toJsonProperties.call(this, result);
        if (this.__jsonProps) {
            for (var k in this.__jsonProps) {
                result[k] = this.__jsonProps[k];
            }
        }
        if (!isEmpty(this.value)) {
            result["value"] = this.value;
        }
    }
    item.prototype.toJsonChildren = function(result) {
        _md.rdbmsBase.prototype.toJsonChildren.call(this, result);
    }
    item.prototype.loadChild = function(child) {
        var name = child.n.toLowerCase();
        if (name === 'value') {
            this.value = child.v; return true;
        }
        return false;
    }
    item.prototype.loadFromNode = function(node) {
        node.children.forEach((item) => {
            var loaded = this.loadChild(item);
            if (!loaded) {
                throw new _md.rdbmsModelException("Tag not recognized: " + item.n, item, this);
            }
        });
    }
    return item;
})(rdbmsBase);

_md.item = item;
// element ittfPanel
var ittfPanel = (function (rdbmsBase) {
    _inherits(ittfPanel, rdbmsBase);
    function ittfPanel(name, sourceLineInfo) {
        _get(Object.getPrototypeOf(ittfPanel.prototype), 'constructor', this).call(this, name,sourceLineInfo);
        _classCallCheck(this, ittfPanel);
        this.wzElement = "ittfPanel";
    }
    ittfPanel.prototype.toJson = function() {
        var result = {};
        this.toJsonProperties(result);
        this.toJsonChildren(result);
        return result;
    }
    ittfPanel.prototype.toJsonProperties = function(result) {
        _md.rdbmsBase.prototype.toJsonProperties.call(this, result);
        if (this.__jsonProps) {
            for (var k in this.__jsonProps) {
                result[k] = this.__jsonProps[k];
            }
        }
    }
    ittfPanel.prototype.toJsonChildren = function(result) {
        _md.rdbmsBase.prototype.toJsonChildren.call(this, result);
    }
    return ittfPanel;
})(rdbmsBase);

_md.ittfPanel = ittfPanel;
_md.__tagElementMapping = { 'ittf-panel': 'ittfPanel', 'ittfpanel': 'ittfPanel' };
// model/replaceUnknownElement( )
var rdbmsModelException = (function () {
    function rdbmsModelException(message, node, instance) {
        _classCallCheck(this, rdbmsModelException);
        // VIA 14/2/21 (pollutes log) set this.node = node
        // VIA 14/2/21 (pollutes log) set this.instance = instance
        if (node && instance) {
            this.message = message + ', wzElement: ' + node.wzElement + ', wzName:' + (node.wzName || '') + ', row:' + node.r + ', col:' + node.c + ', source:' + instance.wzSourceFilepath(node.u);
            this.errorLines = instance.wzSourceErrorLines(node, message);
        }
        else if (instance) {
            this.message = message + instance.wzSourceLineInfo.toString(instance);
        }
        else {
            this.message = message;
        }
        console.error('message', this.message);
        this.stack = (new Error()).stack;
    }
    rdbmsModelException.prototype.toString = function() {
        var msg = [];
        msg.push(chalk.red('Error: ' + this.message));
        msg.push(chalk.red('  name: rdbmsModelException'));
        if (this.node) {
            msg.push(chalk.yellow('  row: ' + this.node.r + ', col: ' + this.node.c));
        }
        if (this.instance) {
            if (this.node) {
                msg.push(chalk.yellow('  uri: ' + this.instance.wzSourceFilepath(this.node.u)));
            }
            else {
                msg.push(chalk.yellow('  uri: ' + this.instance.wzSourceLineInfo.toString(this.instance)));
            }
        }
        else {
            msg.push(chalk.yellow('  uri: unknown'));
        }
        if (this.errorLines) {
            var i, i_items=this.errorLines, i_len=this.errorLines.length, line;
            for (i=0; i<i_len; i++) {
                line = this.errorLines[i];
                msg.push(chalk.yellow('  ' + line));
            }
        }
        return msg.join('\n');
    }
    return rdbmsModelException;
})();

_md.rdbmsModelException = rdbmsModelException;
var rdbmsContext = (function () {
    function rdbmsContext() {
        _classCallCheck(this, rdbmsContext);
        this.validationErrors = [];
    }
    rdbmsContext.prototype.schemaIsValid = function() {
        return this.validationErrors.length == 0;
    }
    rdbmsContext.prototype.addError = function(message, node) {
        var at = node ? ' At ' + node.wzSourceLineInfo.toString(node) : '';
        this.validationErrors.push(message + at);
    }
    return rdbmsContext;
})();

_md.rdbmsContext = rdbmsContext;
function parsestring(value, defaultValue, node) {
    if (isEmpty( value )) {
        return defaultValue;
    }
    return value;
}
function isString(value) {
    return (typeof value === 'string' || value instanceof String);
}
function isEmpty(value) {
    return !isString( value ) || value.length === 0;
}
function isBoolean(value) {
    return value === 'true' || value === 'false';
}

